# Generated by Django 2.2 on 2019-05-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190425_0100'),
        ('api', '0002_auto_20190426_1642'),
    ]

    operations = [
    ]
