# Generated by Django 2.2 on 2019-05-08 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20190509_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='doctor',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patient_diagnosis',
            field=models.CharField(choices=[('I10', 'Arterial hypertension'), ('J42', 'Chronical bronchitis'), ('J06.9', 'cold'), ('M42', 'osteochondrosis'), ('E10', 'diabetes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('cardiologist', 'cardiologist'), ('ophthalmologist', 'ophthalmologist'), ('neuropathologist', 'neuropathologist'), ('surgeon', 'surgeon'), ('otorhinolaryngologist', 'otorhinolaryngologist'), ('endocrinologist', 'endocrinologist')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
