# Generated by Django 2.2.1 on 2019-05-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190510_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Doctor'),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
