# Generated by Django 2.2.1 on 2019-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190513_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
