# Generated by Django 2.1.7 on 2019-05-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
