# Generated by Django 2.2.1 on 2019-05-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190513_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patient_diagnosis',
        ),
    ]
