# Generated by Django 2.2.1 on 2019-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190514_0228'),
    ]

    operations = [

    ]
