# Generated by Django 2.2.1 on 2019-05-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190514_0229'),
    ]

    operations = [

    ]
