# Generated by Django 2.2.1 on 2019-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_profile_email'),
    ]

    operations = [

    ]
