# Generated by Django 2.2.1 on 2019-05-13 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_profile_email'),
    ]

    operations = [

    ]
