# Generated by Django 2.2.1 on 2019-05-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190514_0938'),
    ]

    operations = [

    ]
