# Generated by Django 2.2.1 on 2019-05-14 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190514_0950'),
    ]

    operations = [

    ]
